export const OMI_RULE: string;
export const MASKS: Readonly<Record<string, number>>;
export const BLOCK_73: readonly number[];
export const ORBIT_WIDTH_36: number;
export const BASE36_ALPHABET: string;
export const SELECTOR_16: Readonly<Record<number, string>>;
export const POS_PART_000B: Readonly<Record<number, string>>;
export const NOMOGRAM_0x30_0x3F: Readonly<Record<number, string>>;
export const OMI_GAUGE_ORBIT_0x40_0x4F: Readonly<Record<number, string>>;

export function mask(width: number): number;
export function rotl(x: number, k: number, width?: number): number;
export function rotr(x: number, k: number, width?: number): number;
export function delta(x: number, C?: number, width?: number): number;
export function deltaOrbit(seed: number, C?: number, width?: number, limit?: number): { preperiod: number; period: number; values: number[] };
export function hammingDistance(a: number, b: number): number;
export function onesComplement(x: number, width?: number): number;
export function twosComplementNegate(x: number, width?: number): number;
export function highNibble(byte: number): number;
export function lowNibble(byte: number): number;
export function byteFromNibbles(high: number, low: number): number;
export function twoCubeMirror(byte: number): number;
export function twoCubeDelta(byte: number): number;
export function isDiagonalByte(byte: number): boolean;
export function local240(byte: number): number;
export function byteFromLocal240(index: number): number;
export function gaugeCell16xy(row: number, x: number, y: number): number;
export function gaugeCell4y2(row: number, x: number, y: number): number;
export function decodeGaugeCell16xy(cell: number): { row: number; x: number; y: number };
export function decodeGaugeCell4y2(cell: number): { row: number; x: number; y: number };
export function gaugeFoldWitness24(runtimeRow: number, bridgeRow: number, nomogramRow: number, orbitConstant: number, width?: number): number;
export function isSaturatedGaugeWitness24(witness: number): boolean;
export function qxy(x: number, y: number): number;
export function qxyLocal240(x: number, y: number): number;
export function qxyRoot120(x: number, y: number): number;
export function base36Value(ch: string): number;
export function base36Char(value: number): string;
export function orbit36(position: number): { quotient: number; remainder: number; symbol: string };
export function block73Step(index: number): number;
export function mixedEncode(value: number, radices: number[]): number[];
export function mixedDecode(coords: number[], radices: number[]): number;
export function unicodeDecompose(codepoint: number): { plane: number; offset: number };
export function unicodeCompose(plane: number, offset: number): number;
export function utf16SurrogatePair(codepoint: number): { high: number; low: number };
export function codepointFromSurrogates(high: number, low: number): number;
export function isPrivateUseCodepoint(codepoint: number): boolean;
export function isUnicodeNoncharacter(codepoint: number): boolean;
export function slot5040(fano7: number, role3: number, local: number): number;
export function decodeSlot5040(slot: number): { fano7: number; role3: number; local240: number };
export function factorial(n: number): number;
export function envelopeMultiplier(n: number): number;
export function coordNFactorial(n: number, envelopeIndex: number, local5040: number): number;
export function fanoLineOk(a: number, b: number, c: number): boolean;
export function expand7(x: number): number;
export function closure7(seed: number, lower?: number, upper?: number): number;
export function phase7(x: number): number;
export function carCdrCid(car: number, cdr: number): number;
export function verifyCarCdrCid(car: number, cdr: number, cid: number): boolean;
export function xor16(values: number[]): number;
export function parseOmiAddress(address: string): { segments: number[]; prefix: number };
export function formatOmiAddress(segments: number[], prefix?: number): string;
export function posPartName(value: number): string;
export function selectorName(nibble: number): string;
export function nomogramName(scale: number): string;
export function orbitName(code: number): string;
export function projectArtifact(node: any, plane: "FS" | "GS" | "RS" | "US"): any;
export function verifyPacketXor(payloadBytes: Iterable<number>, fingerprint16: number): boolean;
export function dataViewHeader32(subpath: number, packetClass: number, axis: number, sign?: number): number;
export function decodeDataViewHeader32(word: number): { subpath: number; packetClass: number; axis: number; sign: number };
export function root16FromFragmentsXor(fragments: Array<{idx:number; car:number}>): number;
export function gf256Mul(a: number, b: number, poly?: number): number;
export function gf256Pow(a: number, e: number, poly?: number): number;
export function gf256Inv(a: number, poly?: number): number;
export function gf256Div(a: number, b: number, poly?: number): number;
export function gf256InterpolateAtZero(points: Array<{x:number; y:number}>, poly?: number): number;
export function root16FromFragmentsGF256(fragments: Array<{idx:number; car:number}>, k: number, poly?: number): number;
export function quotientTest(before: unknown, after: unknown): "projection-or-convenience" | "foundational";
